import { createClient } from "@supabase/supabase-js";
import { NextResponse } from "next/server";

const URL = "https://ysbivovfehxqccvbjgbv.supabase.co";

// Breeds data
const BREEDS = [
  {"name":"Labrador Retriever","slug":"labrador-retriever","species":"dog","description":"The Labrador Retriever is the most popular dog breed in the US, UK, and Canada. Friendly, active, and outgoing, Labs excel as family companions and working dogs. As a large breed, they are prone to hip and elbow dysplasia, obesity, and exercise-induced collapse. Routine orthopedic screening and weight management are essential.","akc_group":"Sporting","tica_group":null,"origin":"Canada/United Kingdom","weight_male_kg_low":29,"weight_male_kg_high":36,"weight_female_kg_low":25,"weight_female_kg_high":32,"height_cm_low":55,"height_cm_high":62,"life_expectancy_years_low":10,"life_expectancy_years_high":14,"litter_size_avg":7,"gestation_days":63,"heat_cycle_days":180,"coat_colors":["black","yellow","chocolate","fox red","silver"],"temperament":["friendly","active","outgoing","gentle","intelligent"],"is_featured":true},
  {"name":"German Shepherd Dog","slug":"german-shepherd-dog","species":"dog","description":"The German Shepherd Dog is a large, agile, and muscular working breed known for intelligence, loyalty, and versatility. Health concerns center on hip and elbow dysplasia, degenerative myelopathy, and bloat.","akc_group":"Herding","tica_group":null,"origin":"Germany","weight_male_kg_low":30,"weight_male_kg_high":40,"weight_female_kg_low":22,"weight_female_kg_high":32,"height_cm_low":55,"height_cm_high":65,"life_expectancy_years_low":9,"life_expectancy_years_high":13,"litter_size_avg":8,"gestation_days":63,"heat_cycle_days":180,"coat_colors":["black and tan","sable","black","white","bicolor"],"temperament":["intelligent","loyal","confident","courageous","obedient"],"is_featured":true},
  {"name":"Dachshund","slug":"dachshund","species":"dog","description":"The Dachshund, known as the 'wiener dog', is a small hound with a long body and short legs. The breed's elongated spine makes IVDD the primary health crisis — approximately 25% are affected.","akc_group":"Hound","tica_group":null,"origin":"Germany","weight_male_kg_low":7,"weight_male_kg_high":15,"weight_female_kg_low":7,"weight_female_kg_high":15,"height_cm_low":13,"height_cm_high":23,"life_expectancy_years_low":12,"life_expectancy_years_high":16,"litter_size_avg":4,"gestation_days":63,"heat_cycle_days":180,"coat_colors":["red","black and tan","chocolate and tan","cream","dapple","blue"],"temperament":["curious","stubborn","devoted","playful","brave"],"is_featured":true},
  {"name":"Poodle","slug":"poodle","species":"dog","description":"Poodles come in three size varieties — Standard, Miniature, and Toy — but share a curly, hypoallergenic coat and exceptional intelligence. Prone to Addison's disease, sebaceous adenitis, hip dysplasia, and PRA.","akc_group":"Non-Sporting","tica_group":null,"origin":"Germany/France","weight_male_kg_low":2,"weight_male_kg_high":32,"weight_female_kg_low":2,"weight_female_kg_high":27,"height_cm_low":25,"height_cm_high":60,"life_expectancy_years_low":10,"life_expectancy_years_high":18,"litter_size_avg":5,"gestation_days":63,"heat_cycle_days":180,"coat_colors":["white","black","apricot","brown","silver","red","parti"],"temperament":["intelligent","active","proud","alert","trainable"],"is_featured":true},
  {"name":"English Bulldog","slug":"english-bulldog","species":"dog","description":"The English Bulldog is a muscular, heavy-boned breed with a distinctive wrinkled face and pushed-in nose. Faces severe brachycephalic health challenges including BOAS, skin fold infections, and heat intolerance.","akc_group":"Non-Sporting","tica_group":null,"origin":"United Kingdom","weight_male_kg_low":23,"weight_male_kg_high":25,"weight_female_kg_low":18,"weight_female_kg_high":23,"height_cm_low":31,"height_cm_high":40,"life_expectancy_years_low":8,"life_expectancy_years_high":10,"litter_size_avg":4,"gestation_days":63,"heat_cycle_days":180,"coat_colors":["red brindle","fawn","white","piebald","red"],"temperament":["gentle","courageous","dignified","affectionate","determined"],"is_featured":true},
  {"name":"Boxer","slug":"boxer","species":"dog","description":"The Boxer is a medium-to-large working breed known for boundless energy and loyalty. Predisposed to cancers including lymphoma and mast cell tumors, DCM, aortic stenosis, and hip dysplasia.","akc_group":"Working","tica_group":null,"origin":"Germany","weight_male_kg_low":30,"weight_male_kg_high":35,"weight_female_kg_low":25,"weight_female_kg_high":29,"height_cm_low":53,"height_cm_high":63,"life_expectancy_years_low":10,"life_expectancy_years_high":12,"litter_size_avg":6,"gestation_days":63,"heat_cycle_days":180,"coat_colors":["fawn","brindle","white","reverse brindle"],"temperament":["playful","loyal","energetic","fearless","affectionate"],"is_featured":true},
  {"name":"Beagle","slug":"beagle","species":"dog","description":"The Beagle is a small-to-medium scent hound with a friendly, curious nature. Common concerns include epilepsy, hypothyroidism, IVDD, chronic ear infections, cherry eye, and glaucoma.","akc_group":"Hound","tica_group":null,"origin":"United Kingdom","weight_male_kg_low":10,"weight_male_kg_high":11,"weight_female_kg_low":9,"weight_female_kg_high":10,"height_cm_low":33,"height_cm_high":41,"life_expectancy_years_low":10,"life_expectancy_years_high":15,"litter_size_avg":6,"gestation_days":63,"heat_cycle_days":180,"coat_colors":["tricolor","lemon and white","red and white","blue tick","chocolate tri"],"temperament":["curious","friendly","merry","determined","gentle"],"is_featured":true},
  {"name":"Rottweiler","slug":"rottweiler","species":"dog","description":"The Rottweiler is a large, powerful working breed. The breed faces elevated risks of osteosarcoma, hip and elbow dysplasia, and aortic stenosis. Cancer — particularly osteosarcoma — is the leading cause of death.","akc_group":"Working","tica_group":null,"origin":"Germany","weight_male_kg_low":50,"weight_male_kg_high":60,"weight_female_kg_low":35,"weight_female_kg_high":48,"height_cm_low":56,"height_cm_high":69,"life_expectancy_years_low":8,"life_expectancy_years_high":10,"litter_size_avg":8,"gestation_days":63,"heat_cycle_days":180,"coat_colors":["black and mahogany","black and tan","black and rust"],"temperament":["confident","loyal","courageous","calm","protective"],"is_featured":true},
  {"name":"Persian","slug":"persian","species":"cat","description":"The Persian is a long-haired cat breed with a distinctive round face and calm personality. Predisposed to Polycystic Kidney Disease (affecting up to 40%), HCM, PRA, and brachycephalic respiratory issues.","akc_group":null,"tica_group":"Persian","origin":"Iran","weight_male_kg_low":4,"weight_male_kg_high":5.5,"weight_female_kg_low":3.5,"weight_female_kg_high":5,"height_cm_low":25,"height_cm_high":38,"life_expectancy_years_low":12,"life_expectancy_years_high":17,"litter_size_avg":4,"gestation_days":65,"heat_cycle_days":null,"coat_colors":["white","black","blue","cream","silver","golden","tortoiseshell","calico","bicolor"],"temperament":["calm","gentle","affectionate","quiet","dignified"],"is_featured":true},
  {"name":"Siamese","slug":"siamese","species":"cat","description":"The Siamese is one of the most recognizable cat breeds, known for striking blue eyes, color-pointed coat, and extremely vocal, social personality. Common concerns include PRA, asthma, dental disease, and amyloidosis.","akc_group":null,"tica_group":"Siamese","origin":"Thailand","weight_male_kg_low":3.5,"weight_male_kg_high":5.5,"weight_female_kg_low":3,"weight_female_kg_high":4.5,"height_cm_low":20,"height_cm_high":30,"life_expectancy_years_low":12,"life_expectancy_years_high":20,"litter_size_avg":5,"gestation_days":65,"heat_cycle_days":null,"coat_colors":["seal point","blue point","chocolate point","lilac point","flame point","lynx point"],"temperament":["vocal","affectionate","intelligent","social","demanding"],"is_featured":true}
];

export async function GET() {
  const key = process.env.SUPABASE_SERVICE_ROLE_KEY;
  if (!key) return NextResponse.json({error:"Missing SUPABASE_SERVICE_ROLE_KEY"}, {status:500});
  
  const c = createClient(URL, key);
  const {error} = await c.from("breeds").upsert(BREEDS, {onConflict:"slug"});
  
  if (error) return NextResponse.json({error:error.message}, {status:500});
  
  return NextResponse.json({message:`Seeded ${BREEDS.length} breeds`});
}
