"use client";

import { useEffect, useState } from "react";
import Link from "next/link";

type A = Record<string,any>;

export default function BreedDetail({ params }: { params: Promise<{ slug: string }> }) {
  const [s, setS] = useState("");
  const [b, setB] = useState<A|null>(null);
  const [conds, setC] = useState<A[]>([]);
  const [cl, setCl] = useState<A[]>([]);
  const [gr, setGr] = useState<A[]>([]);
  const [ld, setLd] = useState(true);

  useEffect(()=>{params.then(p=>setS(p.slug))},[])
  useEffect(()=>{if(!s)return;(async()=>{const {supabase}=await import("@/lib/supabase");const r=await supabase.from("breeds").select("*").eq("slug",s).single();if(!r.data){setLd(false);return}setB(r.data);const [a1,a2,a3]=await Promise.all([supabase.from("breed_conditions").select("*,conditions(*)").eq("breed_id",r.data.id),supabase.from("breed_checklists").select("*").eq("breed_id",r.data.id).order("sort_order"),supabase.from("breed_growth_curves").select("*").eq("breed_id",r.data.id).order("age_weeks")]);setC(((a1.data??[])as A[]).map(x=>({...x.conditions,...x,conditions:undefined})));setCl((a2.data??[])as A[]);setGr((a3.data??[])as A[]);setLd(false)})()},[s])

  if(ld)return <div className="flex items-center justify-center min-h-screen"><div className="animate-spin rounded-full h-12 w-12 border-b-2 border-indigo-600"/></div>
  if(!b)return <div className="flex items-center justify-center min-h-screen text-gray-500">Breed not found.</div>

  const male=gr.filter((g:A)=>g.sex==="male"),female=gr.filter((g:A)=>g.sex==="female")
  const cc:Record<string,string>={hereditary:"bg-red-500",orthopedic:"bg-amber-500",cardiac:"bg-pink-500",ocular:"bg-blue-500",respiratory:"bg-cyan-500",dermatological:"bg-orange-500",neurological:"bg-purple-500",endocrine:"bg-teal-500",urinary:"bg-indigo-500",reproductive:"bg-rose-500",dental:"bg-emerald-500",other:"bg-gray-500"}
  const fq:Record<string,A>={daily:{c:"bg-red-100 text-red-700",l:"Daily"},weekly:{c:"bg-amber-100 text-amber-700",l:"Weekly"},monthly:{c:"bg-blue-100 text-blue-700",l:"Monthly"},quarterly:{c:"bg-purple-100 text-purple-700",l:"Quarterly"},annually:{c:"bg-green-100 text-green-700",l:"Annually"}}

  return (<div className="min-h-screen bg-white text-gray-900">
    <header className="border-b border-gray-100 bg-white/80 backdrop-blur sticky top-0 z-50"><div className="mx-auto flex max-w-6xl items-center justify-between px-6 py-4"><Link href="/" className="text-xl font-bold"><span className="text-indigo-600">Paw</span>Port</Link><Link href="/" className="text-sm text-gray-500 hover:text-indigo-600">← All Breeds</Link></div></header>
    <section className="bg-gradient-to-br from-indigo-50 via-white to-amber-50 py-16"><div className="mx-auto max-w-6xl px-6"><div className="flex flex-wrap gap-3 mb-4"><span className="rounded-full bg-indigo-100 px-3 py-1 text-xs font-semibold text-indigo-700">{b.species==="dog"?"🐶 Dog":"🐱 Cat"}</span>{b.akc_group?<span className="rounded-full bg-gray-100 px-3 py-1 text-xs text-gray-600">AKC: {b.akc_group}</span>:null}{b.tica_group?<span className="rounded-full bg-gray-100 px-3 py-1 text-xs text-gray-600">TICA: {b.tica_group}</span>:null}<span className="rounded-full bg-gray-100 px-3 py-1 text-xs text-gray-600">{b.origin}</span></div><h1 className="text-4xl font-extrabold">{b.name}</h1><p className="mt-4 max-w-2xl text-gray-600">{b.description}</p></div></section>
    <section className="border-b border-gray-100"><div className="mx-auto grid max-w-6xl grid-cols-2 sm:grid-cols-4 divide-x divide-gray-100">{[["Weight (Male)",b.weight_male_kg_low+"–"+b.weight_male_kg_high+" kg"],["Weight (Female)",b.weight_female_kg_low+"–"+b.weight_female_kg_high+" kg"],["Height",b.height_cm_low+"–"+b.height_cm_high+" cm"],["Lifespan",b.life_expectancy_years_low+"–"+b.life_expectancy_years_high+" years"]].map(([l,v]:string[])=><div key={l} className="px-6 py-4 text-center"><div className="text-xs text-gray-400 uppercase tracking-wider">{l}</div><div className="mt-1 text-sm font-bold">{v}</div></div>)}</div></section>
    <div className="mx-auto max-w-6xl px-6 py-12"><div className="grid gap-12 lg:grid-cols-3"><div className="lg:col-span-2 space-y-12">
      <section><h2 className="text-2xl font-bold">🩺 Health Conditions</h2><p className="mt-1 text-sm text-gray-500">{conds.length} conditions tracked.</p><div className="mt-6 space-y-4">{conds.map((c:A)=>{const sev=Number(c.severity_score)||0;const cat=cc[c.category]||"bg-gray-500";return(<details key={c.id} className="group rounded-xl border border-gray-100 bg-white p-5 shadow-sm"><summary className="flex cursor-pointer items-start justify-between list-none"><div className="flex-1"><div className="flex flex-wrap items-center gap-2"><h3 className="font-bold">{c.name}</h3><span className={"rounded-full px-2 py-0.5 text-xs text-white "+cat}>{c.category}</span>{sev>0?<span className="text-xs text-gray-400">{"★".repeat(sev)}{"☆".repeat(5-sev)}</span>:null}</div>{c.prevalence_rate?<p className="mt-1 text-sm text-indigo-600 font-medium">~{c.prevalence_rate}% affected</p>:null}</div><span className="text-gray-300 group-open:rotate-180">▼</span></summary><div className="mt-4 space-y-3 border-t border-gray-50 pt-4 text-sm"><p className="text-gray-600">{c.description}</p>{c.age_of_onset?<p><b>Onset:</b> {c.age_of_onset}</p>:null}{c.screening_test?<p><b>Screening:</b> {c.screening_test}</p>:null}{c.screening_freq?<p><b>Frequency:</b> {c.screening_freq}</p>:null}{Array.isArray(c.symptoms)&&c.symptoms.length>0?<div><b>Symptoms:</b><div className="mt-1 flex flex-wrap gap-1">{c.symptoms.map((s:string,i:number)=><span key={i} className="rounded bg-red-50 px-2 py-0.5 text-xs text-red-700">{s}</span>)}</div></div>:null}{c.notes?<p className="rounded-lg bg-amber-50 p-3 text-amber-800">💡 {c.notes}</p>:null}</div></details>)})}</div></section>
      {male.length>0?<section><h2 className="text-2xl font-bold">📈 Growth Curve</h2><div className="mt-6 overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b border-gray-200 text-left text-xs uppercase text-gray-400"><th className="pb-2">Weeks</th><th className="pb-2">♂P5</th><th className="pb-2">♂P50</th><th className="pb-2">♂P95</th><th className="pb-2">♀P5</th><th className="pb-2">♀P50</th><th className="pb-2">♀P95</th></tr></thead><tbody>{male.map((m:A)=>{const f=female.find((x:A)=>x.age_weeks===m.age_weeks);return(<tr key={m.age_weeks} className="border-b border-gray-50"><td className="py-2 font-medium">{m.age_weeks}</td><td className="py-2">{m.weight_kg_p5}</td><td className="py-2 font-semibold">{m.weight_kg_p50}</td><td className="py-2">{m.weight_kg_p95}</td><td className="py-2">{f?f.weight_kg_p5:"—"}</td><td className="py-2 font-semibold">{f?f.weight_kg_p50:"—"}</td><td className="py-2">{f?f.weight_kg_p95:"—"}</td></tr>)})}</tbody></table></div></section>:null}
    </div>
    <aside className="space-y-8"><div className="rounded-2xl border border-gray-100 bg-gray-50 p-6"><h3 className="font-bold">Quick Facts</h3><dl className="mt-4 space-y-3 text-sm"><div className="flex justify-between"><dt className="text-gray-500">Litter</dt><dd className="font-medium">{b.litter_size_avg} avg</dd></div><div className="flex justify-between"><dt className="text-gray-500">Gestation</dt><dd className="font-medium">{b.gestation_days}d</dd></div>{b.heat_cycle_days?<div className="flex justify-between"><dt className="text-gray-500">Heat Cycle</dt><dd className="font-medium">~{b.heat_cycle_days}d</dd></div>:null}</dl></div><div className="rounded-2xl border border-gray-100 p-6"><h3 className="font-bold">Temperament</h3><div className="mt-3 flex flex-wrap gap-2">{(Array.isArray(b.temperament)?b.temperament:[]).map((t:string)=><span key={t} className="rounded-full bg-indigo-50 px-3 py-1 text-xs text-indigo-700">{t}</span>)}</div></div><div className="rounded-2xl border border-gray-100 p-6"><h3 className="font-bold">Coat Colors</h3><div className="mt-3 flex flex-wrap gap-2">{(Array.isArray(b.coat_colors)?b.coat_colors:[]).map((c:string)=><span key={c} className="rounded-full bg-amber-50 px-3 py-1 text-xs text-amber-700">{c}</span>)}</div></div></aside></div></div>
    <section className="bg-gray-50 py-12"><div className="mx-auto max-w-6xl px-6"><h2 className="text-2xl font-bold">📋 Daily Care Checklist</h2><div className="mt-6 space-y-3">{cl.map((i:A)=>{const f=fq[i.frequency]||{c:"bg-gray-100 text-gray-600",l:i.frequency};return(<details key={i.id} className="group rounded-xl border border-gray-100 bg-white p-4 shadow-sm"><summary className="flex cursor-pointer items-center justify-between list-none"><div className="flex items-center gap-3"><span className={"rounded-full px-2.5 py-0.5 text-xs font-semibold "+f.c}>{f.l}</span><span className="font-medium">{i.task_name}</span></div><span className="text-gray-300 group-open:rotate-180">▼</span></summary><div className="mt-3 border-t border-gray-50 pt-3 text-sm text-gray-600"><p>{i.description}</p>{Array.isArray(i.warning_signs)&&i.warning_signs.length>0?<div className="mt-2"><span className="font-semibold text-red-600">⚠ </span><div className="mt-1 flex flex-wrap gap-1">{i.warning_signs.map((w:string,j:number)=><span key={j} className="rounded bg-red-50 px-2 py-0.5 text-xs text-red-700">{w}</span>)}</div></div>:null}</div></details>)})}</div></div></section>
    <footer className="border-t border-gray-100 bg-white py-8"><div className="mx-auto max-w-6xl px-6 text-center text-sm text-gray-400"><Link href="/" className="font-bold text-gray-700"><span className="text-indigo-600">Paw</span>Port</Link><span className="ml-4">© 2026</span></div></footer>
  </div>);
}
